# Generated by Django 2.2.7 on 2019-11-05 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_compra', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_validade', models.DateTimeField()),
                ('quantidade', models.IntegerField(default=0)),
                ('armazenamento', models.CharField(choices=[('GLD', 'Geladeira'), ('FRZ', 'Freezer'), ('ARM', 'Armário'), ('ALV', 'Ar livre')], default='ARLIVRE', max_length=4)),
            ],
        ),
    ]
